# Generated by Django 3.0 on 2021-08-12 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=250)),
                ('apellidos', models.CharField(max_length=250)),
                ('cedula', models.CharField(max_length=10)),
                ('celular', models.CharField(max_length=10)),
                ('correo', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='appAgua.Persona')),
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('usuarioAgua', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
            bases=('appAgua.persona',),
        ),
        migrations.CreateModel(
            name='Tesorero',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='appAgua.Persona')),
                ('idTesorero', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('usuarioTesorero', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tesorero',
                'verbose_name_plural': 'Tesoreros',
            },
            bases=('appAgua.persona',),
        ),
        migrations.CreateModel(
            name='ServicioAgua',
            fields=[
                ('idServicioAgua', models.AutoField(primary_key=True, serialize=False)),
                ('costoActivacion', models.DecimalField(decimal_places=2, max_digits=4)),
                ('motivoSuspension', models.TextField()),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('usuario', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='appAgua.Usuario')),
            ],
            options={
                'verbose_name': 'Servicio de Agua',
                'verbose_name_plural': 'Servicios de Agua',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('idPago', models.AutoField(primary_key=True, serialize=False)),
                ('mesDesde', models.DateField()),
                ('mesHasta', models.DateField()),
                ('costoServicio', models.DecimalField(decimal_places=2, max_digits=4)),
                ('tesorero', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='appAgua.Tesorero')),
                ('usuario', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='appAgua.Usuario')),
            ],
            options={
                'verbose_name': 'Pago de Agua',
                'verbose_name_plural': 'Pagos de Agua',
            },
        ),
    ]
