# Generated by Django 2.1.2 on 2021-09-12 23:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appAgua', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialServicio',
            fields=[
                ('idHistorial', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=250)),
                ('costoActivacion', models.DecimalField(decimal_places=2, max_digits=4)),
                ('motivoSuspension', models.TextField()),
                ('fechaSuspension', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Historial de Servicio',
                'verbose_name_plural': 'Historial de Servicios',
            },
        ),
        migrations.RemoveField(
            model_name='tesorero',
            name='usuarioTesorero',
        ),
        migrations.AlterField(
            model_name='pago',
            name='tesorero',
            field=models.ForeignKey(default='--Seleccione un tesorero--', on_delete=django.db.models.deletion.CASCADE, to='appAgua.Tesorero'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='usuario',
            field=models.ForeignKey(default='--Seleccione un usuario--', on_delete=django.db.models.deletion.CASCADE, to='appAgua.Usuario'),
        ),
        migrations.AlterField(
            model_name='servicioagua',
            name='usuario',
            field=models.OneToOneField(default='--Seleccione un usuario--', on_delete=django.db.models.deletion.CASCADE, to='appAgua.Usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usuarioAgua',
            field=models.OneToOneField(default='--Seleccione un usuario--', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
